In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv('hs_data_all_fields.csv', index_col=0)
data.drop(labels=['Freshmen_On_Track_CPS_Pct_Year_2','Graduation_4_Year_School_Pct_Year_2','Graduation_4_Year_School_Pct_Year_1','Graduation_5_Year_School_Pct_Year_1','College_Enrollment_CPS_Pct_Year_2','College_Enrollment_School_Pct_Year_1','College_Persistence_CPS_Pct_Year_2','Mobility_Rate_Pct','College_Persistence_School_Pct_Year_1','College_Persistence_CPS_Pct_Year_1','College_Enrollment_CPS_Pct_Year_1','Graduation_5_Year_CPS_Pct_Year_1','Graduation_5_Year_CPS_Pct_Year_2','Graduation_4_Year_CPS_Pct_Year_1','Graduation_4_Year_CPS_Pct_Year_2','Freshmen_On_Track_School_Pct_Year_1','Freshmen_On_Track_CPS_Pct_Year_1','Unnamed: 0.1','School_Hours','Legacy_Unit_ID','Finance_ID','Short_Name','Summary','Primary_Category','Is_High_School','Is_Middle_School','Is_Elementary_School','Is_Pre_School','Administrator_Title','Administrator','Phone','Secondary_Contact_Title','Secondary_Contact','Address','City','State','Zip','Fax','Freshman_Start_End_Time','After_School_Hours','Earliest_Drop_Off_Time','Significantly_Modified','Blue_Ribbon_Award_Year','Spot_Light_Award_Year','Improvement_Award_Year','Excellence_Award_Year','Hard_Of_Hearing','Mean_ACT','College_Enrollment_Rate_Mean','School_Year','Progress_Report_Year','Graduation_Rate_Mean','Visual_Impairments','School_Latitude','Classroom_Languages','CPS_School_Profile','Website','Facebook','Twitter','Youtube','Pinterest','Attendance_Boundaries','Grades_Offered_All','Grades_Offered','Student_Count_Native_American','Student_Count_Other_Ethnicity','Student_Count_Asian_Pacific_Islander','Student_Count_Multi','Student_Count_Hawaiian_Pacific_Islander','Student_Count_Ethnicity_Not_Available','Statistics_Description','Demographic_Description','PreK_School_Day','Kindergarten_School_Day','PreSchool_Inclusive','Preschool_Instructional','School_Longitude','School_Longitude','Rating_Statement','Classification_Description','Third_Contact_Title','Third_Contact_Name','Fourth_Contact_Title','Fourth_Contact_Name','Fifth_Contact_Title','Fifth_Contact_Name','Sixth_Contact_Title','Sixth_Contact_Name','Seventh_Contact_Title','Seventh_Contact_Name','Location','Excelerate_Award_Gold_Year','Student_Growth_Description','Growth_Reading_Grades_Tested_Pct_ES','Growth_Reading_Grades_Tested_Label_ES','Growth_Math_Grades_Tested_Pct_ES','Growth_Math_Grades_Tested_Label_ES','Student_Attainment_Description','Attainment_Reading_Pct_ES','Attainment_Reading_Lbl_ES','Attainment_Math_Pct_ES','Attainment_Math_Lbl_ES','Culture_Climate_Description','School_Survey_Student_Response_Rate_Avg_Pct','School_Survey_Teacher_Response_Rate_Avg_Pct','Healthy_School_Certification','Healthy_School_Certification_Description','School_Survey_Student_Response_Rate_Pct','School_Survey_Teacher_Response_Rate_Pct','Creative_School_Certification','Creative_School_Certification_Description','NWEA_Reading_Growth_Grade_3_Pct','NWEA_Reading_Growth_Grade_3_Lbl','NWEA_Reading_Growth_Grade_4_Pct','NWEA_Reading_Growth_Grade_4_Lbl','NWEA_Reading_Growth_Grade_5_Pct','NWEA_Reading_Growth_Grade_5_Lbl','NWEA_Reading_Growth_Grade_6_Pct','NWEA_Reading_Growth_Grade_6_Lbl','NWEA_Reading_Growth_Grade_7_Pct','NWEA_Reading_Growth_Grade_7_Lbl','NWEA_Reading_Growth_Grade_8_Pct','NWEA_Reading_Growth_Grade_8_Lbl','NWEA_Math_Growth_Grade_3_Pct','NWEA_Math_Growth_Grade_3_Lbl','NWEA_Math_Growth_Grade_4_Pct','NWEA_Math_Growth_Grade_4_Lbl','NWEA_Math_Growth_Grade_5_Pct','NWEA_Math_Growth_Grade_5_Lbl','NWEA_Math_Growth_Grade_6_Pct','NWEA_Math_Growth_Grade_6_Lbl','NWEA_Math_Growth_Grade_7_Pct','NWEA_Math_Growth_Grade_7_Lbl','NWEA_Math_Growth_Grade_8_Pct','NWEA_Math_Growth_Grade_8_Lbl','NWEA_Reading_Attainment_Grade_2_Pct','NWEA_Reading_Attainment_Grade_2_Lbl','NWEA_Reading_Attainment_Grade_3_Pct','NWEA_Reading_Attainment_Grade_3_Lbl','NWEA_Reading_Attainment_Grade_4_Pct','NWEA_Reading_Attainment_Grade_4_Lbl','NWEA_Reading_Attainment_Grade_5_Pct','NWEA_Reading_Attainment_Grade_5_Lbl','NWEA_Reading_Attainment_Grade_6_Pct','NWEA_Reading_Attainment_Grade_6_Lbl','NWEA_Reading_Attainment_Grade_7_Pct','NWEA_Reading_Attainment_Grade_7_Lbl','NWEA_Reading_Attainment_Grade_8_Pct','NWEA_Reading_Attainment_Grade_8_Lbl','NWEA_Math_Attainment_Grade_2_Pct','NWEA_Math_Attainment_Grade_2_Lbl','NWEA_Math_Attainment_Grade_3_Pct','NWEA_Math_Attainment_Grade_3_Lbl','NWEA_Math_Attainment_Grade_4_Pct','NWEA_Math_Attainment_Grade_4_Lbl','NWEA_Math_Attainment_Grade_5_Pct','NWEA_Math_Attainment_Grade_5_Lbl','NWEA_Math_Attainment_Grade_6_Pct','NWEA_Math_Attainment_Grade_6_Lbl','NWEA_Math_Attainment_Grade_7_Pct','NWEA_Math_Attainment_Grade_7_Lbl','NWEA_Math_Attainment_Grade_8_Pct','NWEA_Math_Attainment_Grade_8_Lbl','Suspensions_Per_100_Students_Avg_Pct','Misconducts_To_Suspensions_Avg_Pct','Average_Length_Suspension_Year_1_Pct','Average_Length_Suspension_Year_2_Pct','Average_Length_Suspension_Avg_Pct','Behavior_Discipline_Year_1','Behavior_Discipline_Year_2','Student_Attendance_Avg_Pct','Teacher_Attendance_Avg_Pct','One_Year_Dropout_Rate_Avg_Pct','Other_Metrics_Year_1','Other_Metrics_Year_2','Growth_ACT_Grade_11_Lbl','Attainment_ACT_Grade_11_Lbl','Progress_Toward_Graduation_Year_1','Progress_Toward_Graduation_Year_2','State_School_Report_Card_URL','Chronic_Truancy_Pct','Empty_Progress_Report_Message','School_Survey_Rating_Description','Supportive_School_Award_Desc','Parent_Survey_Results_Year','School_Latitude.1','School_Longitude.1','Transportation_Bus','Transportation_El','Transportation_Metra'], axis=1,inplace=True)
data.set_index('School_ID', inplace=True)
name=data['Long_Name']
data.drop(labels='Long_Name', axis=1, inplace=True)
data=data[-data['Graduation_Rate_School'].isna()]
data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
School_Type,121,10,Neighborhood,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Student_Count_Total,121,NaN,NaN,NaN,768.182,684.097,38,307,556,1062,4447
Student_Count_Low_Income,121,NaN,NaN,NaN,617.364,474.683,37,271,479,855,2713
Student_Count_Special_Ed,121,NaN,NaN,NaN,114.174,77.857,6,58,89,161,394
Student_Count_English_Learners,121,NaN,NaN,NaN,63.5537,93.8282,0,4,20,80,502
Student_Count_Black,121,NaN,NaN,NaN,284.091,287.303,1,90,196,355,1468
Student_Count_Hispanic,121,NaN,NaN,NaN,353.603,463.267,1,13,145,539,2377
Student_Count_White,121,NaN,NaN,NaN,77.5289,227.987,0,1,4,34,1567
Student_Count_Asian,121,NaN,NaN,NaN,35.595,86.5742,0,0,1,10,469
ADA_Accessible,121,3,Generally accessible,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dress_Code,121,2,Y,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bilingual_Services,115,2,Y,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Refugee_Services,113,2,N,107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Title_1_Eligible,121,2,Y,111,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Average_ACT_School,117,NaN,NaN,NaN,17.4675,3.1528,13.1,15.2,16.8,18.5,29.6
College_Enrollment_Rate_School,119,NaN,NaN,NaN,58.5311,19.1035,0,45.5,59.5,74.65,93.4
Graduation_Rate_School,121,NaN,NaN,NaN,72.8917,19.3645,0,67.9,76.3,85.2,97.8
Overall_Rating,121,6,Level 1+,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating_Status,121,4,Good Standing,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Student_Growth_Rating,121,6,BELOW AVERAGE,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Student_Attainment_Rating,121,6,BELOW AVERAGE,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Culture_Climate_Rating,121,6,WELL ORGANIZED,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Involved_Families,121,6,STRONG,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Supportive_Environment,121,5,NEUTRAL,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Ambitious_Instruction,121,6,STRONG,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Effective_Leaders,121,6,NEUTRAL,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Collaborative_Teachers,121,5,NEUTRAL,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Safety,121,6,WEAK,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suspensions_Per_100_Students_Year_1_Pct,88,NaN,NaN,NaN,26.9932,33.0335,0,5.075,14.75,32.925,188.7
Suspensions_Per_100_Students_Year_2_Pct,88,NaN,NaN,NaN,26.8284,33.4817,0,5.925,11.95,32.8,193.4
Misconducts_To_Suspensions_Year_1_Pct,88,NaN,NaN,NaN,28.7852,20.5192,0,14.075,23.6,38.975,95.4
Misconducts_To_Suspensions_Year_2_Pct,88,NaN,NaN,NaN,29.917,22.6572,0,14.3,22.4,39.25,100
School_Survey_School_Community,121,4,NOT ENOUGH DATA,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Parent_Teacher_Partnership,121,5,NOT ENOUGH DATA,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School_Survey_Quality_Of_Facilities,121,5,NOT ENOUGH DATA,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Student_Attendance_Year_1_Pct,121,NaN,NaN,NaN,89.4182,5.6008,61.2,86.9,90.5,93.3,97.9
Student_Attendance_Year_2_Pct,121,NaN,NaN,NaN,89.0264,6.80316,43.6,87,90.6,93.2,98
Teacher_Attendance_Year_1_Pct,85,NaN,NaN,NaN,94.7788,0.932112,92.5,94,94.9,95.5,97.6
Teacher_Attendance_Year_2_Pct,85,NaN,NaN,NaN,90.1247,0.797452,88.4,89.6,90.1,90.6,92.1
One_Year_Dropout_Rate_Year_1_Pct,119,NaN,NaN,NaN,4.88571,4.75497,0,1.9,3.7,6.45,32.3
One_Year_Dropout_Rate_Year_2_Pct,119,NaN,NaN,NaN,4.33445,4.69577,0,1.6,2.9,5.45,33.9
Growth_ACT_Grade_11_Pct,114,NaN,NaN,NaN,-0.0622807,1.4267,-2.5,-1,-0.4,0.6,4.2
Attainment_ACT_Grade_11_Pct,117,NaN,NaN,NaN,29.6496,24.9463,3,11,22,40,99
Freshmen_On_Track_School_Pct_Year_2,117,NaN,NaN,NaN,84.7205,11.6924,40,78.3,87.1,93.2,100
Graduation_5_Year_School_Pct_Year_2,121,NaN,NaN,NaN,72.8917,19.3645,0,67.9,76.3,85.2,97.8
College_Enrollment_School_Pct_Year_2,119,NaN,NaN,NaN,58.5311,19.1035,0,45.5,59.5,74.65,93.4
College_Persistence_School_Pct_Year_2,115,NaN,NaN,NaN,65.8061,15.3849,29.6,58.55,67.5,76.9,97.4
Supportive_School_Award,121,4,Coming Soon,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lib_cnt,121,NaN,NaN,NaN,4.29752,2.17426,0,3,4,5,11
Neighborhood Name,121,57,NEAR WEST SIDE,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRED_NON_ENG_LANG,121,4,SPANISH,108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRED_NON_ENG_PERCENT,121,NaN,NaN,NaN,0.114876,0.145826,0,0.01,0.04,0.18,0.45
PERCENT OF HOUSING CROWDED,121,NaN,NaN,NaN,0.0563636,0.0430064,0.003,0.025,0.039,0.074,0.158
PERCENT HOUSEHOLDS BELOW POVERTY,121,NaN,NaN,NaN,0.240306,0.105995,0.034,0.147,0.217,0.298,0.565
PERCENT AGED 16+ UNEMPLOYED,121,NaN,NaN,NaN,0.159686,0.0718371,0.047,0.1,0.158,0.208,0.359
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,121,NaN,NaN,NaN,0.223215,0.135779,0.025,0.129,0.177,0.285,0.548
PERCENT AGED UNDER 18 OR OVER 64,121,NaN,NaN,NaN,0.341702,0.0787906,0.135,0.307,0.369,0.396,0.515
PER CAPITA INCOME,121,NaN,NaN,NaN,25269.2,15306.8,8201,13785,19713,33385,88669
HARDSHIP INDEX,121,NaN,NaN,NaN,52.5785,30.5059,1,26,52,83,98

In the above step we are deleting irrelevant column names, subsetting the data to school that have graduation rate value filled out, separating names of schools for future use if needed, changing index to school id.

Next step is to create change values from fields that have year 1 and year 2 and drop original variables

In [2]:
data['Suspensions_Per_100_Students_Change']=data['Suspensions_Per_100_Students_Year_1_Pct']-data['Suspensions_Per_100_Students_Year_2_Pct']
data['Misconducts_To_Suspensions_Change']=data['Misconducts_To_Suspensions_Year_1_Pct']-data['Misconducts_To_Suspensions_Year_2_Pct']
data['Student_Attendance_Change']=data['Student_Attendance_Year_1_Pct']-data['Student_Attendance_Year_2_Pct']
data['Teacher_Attendance_Change']=data['Teacher_Attendance_Year_1_Pct']-data['Teacher_Attendance_Year_2_Pct']
data['One_Year_Dropout_Rate_Change']=data['One_Year_Dropout_Rate_Year_1_Pct']-data['One_Year_Dropout_Rate_Year_2_Pct']
data.drop(labels=['College_Enrollment_School_Pct_Year_2','Graduation_5_Year_School_Pct_Year_2','Suspensions_Per_100_Students_Year_1_Pct','Suspensions_Per_100_Students_Year_2_Pct','Misconducts_To_Suspensions_Year_1_Pct','Misconducts_To_Suspensions_Year_2_Pct','Student_Attendance_Year_1_Pct','Student_Attendance_Year_2_Pct','Teacher_Attendance_Year_1_Pct','Teacher_Attendance_Year_2_Pct','One_Year_Dropout_Rate_Year_1_Pct','One_Year_Dropout_Rate_Year_2_Pct'],axis=1,inplace=True)

Following step fills in null values:

average for missing values of ACT Score, college enrollment rate, and other percent values related to school or college performance

zeroes for rates of change from previous year; we are assuming that schools that had missing values for suspension, misconduct, teacher attendance and one year drop out rates, had no changces from 2015 to 2016

U for unknown for categorical values that otherwise have a Y/N indicator

In [3]:
data['Average_ACT_School'].fillna(data['Average_ACT_School'].mean(),inplace=True)
data['College_Enrollment_Rate_School'].fillna(data['College_Enrollment_Rate_School'].mean(),inplace=True)
data['Growth_ACT_Grade_11_Pct'].fillna(data['Growth_ACT_Grade_11_Pct'].mean(),inplace=True)
data['Attainment_ACT_Grade_11_Pct'].fillna(data['Attainment_ACT_Grade_11_Pct'].mean(),inplace=True)
data['Freshmen_On_Track_School_Pct_Year_2'].fillna(data['Freshmen_On_Track_School_Pct_Year_2'].mean(),inplace=True)
data['College_Persistence_School_Pct_Year_2'].fillna(data['College_Persistence_School_Pct_Year_2'].mean(),inplace=True)

data['Suspensions_Per_100_Students_Change'].fillna(0,inplace=True)
data['Misconducts_To_Suspensions_Change'].fillna(0,inplace=True)
data['Teacher_Attendance_Change'].fillna(0,inplace=True)
data['One_Year_Dropout_Rate_Change'].fillna(0,inplace=True)

data['Bilingual_Services'].fillna('U',inplace=True)
data['Refugee_Services'].fillna('U',inplace=True)

Some values in the data set had counts of students in the school that were part of a group (low income, special ed, different ethnic groups, etc). We calculated rates for those groups using provided counts and student total count for the school. Then, dropped the original count columns.

In [4]:
data['Student_Low_Income_Pct']=data['Student_Count_Low_Income']/data['Student_Count_Total']
data['Student_Special_Ed_Pct']=data['Student_Count_Special_Ed']/data['Student_Count_Total']
data['Student_English_Learners_Pct']=data['Student_Count_English_Learners']/data['Student_Count_Total']
data['Student_Black_Pct']=data['Student_Count_Black']/data['Student_Count_Total']
data['Student_Hispanic_Pct']=data['Student_Count_Hispanic']/data['Student_Count_Total']
data['Student_White_Pct']=data['Student_Count_White']/data['Student_Count_Total']
data['Student_Asian_Pct']=data['Student_Count_Asian']/data['Student_Count_Total']

data.drop(labels=['Student_Count_Low_Income','Student_Count_Special_Ed','Student_Count_English_Learners','Student_Count_Black','Student_Count_Hispanic','Student_Count_White','Student_Count_Asian'], axis=1,inplace=True)

In the following step we are creating a new dataset with dummies for categorical variables

In [5]:
data_dummies=pd.get_dummies(data)

Next step is to create another dataset with all variables scaled from 0 to 1. This data set will be used for regression modeling.

In [6]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit(data_dummies)
data_scaled=pd.DataFrame(min_max.transform(data_dummies),index=data_dummies.index.values,columns=data_dummies.columns.values)

pd.set_option('display.max_columns', 100)
data_scaled.describe(include='all').T

,count,mean,std,min,25%,50%,75%,max
Student_Count_Total,121.0,0.165612,0.155159,0.0,0.061012,0.117487,0.232252,1.0
Average_ACT_School,121.0,0.264698,0.187867,0.0,0.127273,0.230303,0.327273,1.0
College_Enrollment_Rate_School,121.0,0.626671,0.202823,0.0,0.489293,0.635974,0.798715,1.0
Graduation_Rate_School,121.0,0.745314,0.198001,0.0,0.694274,0.780164,0.871166,1.0
Growth_ACT_Grade_11_Pct,121.0,0.363839,0.206636,0.0,0.223881,0.328358,0.462687,1.0
Attainment_ACT_Grade_11_Pct,121.0,0.277600,0.255489,0.0,0.083333,0.208333,0.375000,1.0
Freshmen_On_Track_School_Pct_Year_2,121.0,0.745342,0.191599,0.0,0.670000,0.776667,0.886667,1.0
College_Persistence_School_Pct_Year_2,121.0,0.534013,0.221170,0.0,0.442478,0.547198,0.694690,1.0
lib_cnt,121.0,0.390684,0.197660,0.0,0.272727,0.363636,0.454545,1.0
PRED_NON_ENG_PERCENT,121.0,0.255280,0.324058,0.0,0.022222,0.088889,0.400000,1.0
PERCENT OF HOUSING CROWDED,121.0,0.344282,0.277461,0.0,0.141935,0.232258,0.458065,1.0
PERCENT HOUSEHOLDS BELOW POVERTY,121.0,0.388523,0.199614,0.0,0.212806,0.344633,0.497175,1.0
PERCENT AGED 16+ UNEMPLOYED,121.0,0.361173,0.230247,0.0,0.169872,0.355769,0.516026,1.0
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,121.0,0.378996,0.259615,0.0,0.198853,0.290631,0.497132,1.0
PERCENT AGED UNDER 18 OR OVER 64,121.0,0.543954,0.207344,0.0,0.452632,0.615789,0.686842,1.0
PER CAPITA INCOME,121.0,0.212112,0.190222,0.0,0.069394,0.143063,0.312969,1.0
HARDSHIP INDEX,121.0,0.531737,0.314494,0.0,0.257732,0.525773,0.845361,1.0
Suspensions_Per_100_Students_Change,121.0,0.497658,0.094905,0.0,0.489929,0.497006,0.511704,1.0
Misconducts_To_Suspensions_Change,121.0,0.460626,0.161228,0.0,0.411137,0.470379,0.509479,1.0
Student_Attendance_Change,121.0,0.130348,0.094966,0.0,0.101770,0.121681,0.146018,1.0
Teacher_Attendance_Change,121.0,0.527326,0.352256,0.0,0.000000,0.709677,0.774194,1.0
One_Year_Dropout_Rate_Change,121.0,0.445522,0.127153,0.0,0.394595,0.427027,0.497297,1.0
Student_Low_Income_Pct,121.0,0.808827,0.207230,0.0,0.773343,0.886989,0.927222,1.0
Student_Special_Ed_Pct,121.0,0.169600,0.139432,0.0,0.091055,0.149572,0.221196,1.0
Student_English_Learners_Pct,121.0,0.204971,0.245138,0.0,0.019823,0.115482,0.297831,1.0
Student_Black_Pct,121.0,0.519915,0.388664,0.0,0.121060,0.441468,0.969429,1.0
Student_Hispanic_Pct,121.0,0.387639,0.347367,0.0,0.024435,0.329032,0.710146,1.0
Student_White_Pct,121.0,0.120364,0.212846,0.0,0.004559,0.024917,0.117013,1.0
Student_Asian_Pct,121.0,0.083004,0.170391,0.0,0.000000,0.007328,0.069603,1.0
School_Type_Career academy,121.0,0.033058,0.179531,0.0,0.000000,0.000000,0.000000,1.0
...,...,...,...,...,...,...,...,...
Neighborhood Name_MOUNT GREENWOOD,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NEAR NORTH SIDE,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NEAR SOUTH SIDE,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NEAR WEST SIDE,121.0,0.074380,0.263480,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NEW CITY,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NORTH CENTER,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NORTH LAWNDALE,121.0,0.024793,0.156141,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NORTH PARK,121.0,0.033058,0.179531,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_NORWOOD PARK,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_PORTAGE PARK,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_PULLMAN,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_RIVERDALE,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_ROGERS PARK,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_ROSELAND,121.0,0.024793,0.156141,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_SOUTH CHICAGO,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_SOUTH LAWNDALE,121.0,0.057851,0.234433,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_SOUTH SHORE,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_UPTOWN,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WASHINGTON HEIGHTS,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WASHINGTON PARK,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WEST ELSDON,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WEST ENGLEWOOD,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WEST LAWN,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WEST RIDGE,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WEST TOWN,121.0,0.057851,0.234433,0.0,0.000000,0.000000,0.000000,1.0
Neighborhood Name_WOODLAWN,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
PRED_NON_ENG_LANG_AFRICAN LANGUAGES,121.0,0.008264,0.090909,0.0,0.000000,0.000000,0.000000,1.0
PRED_NON_ENG_LANG_CHINESE,121.0,0.082645,0.276489,0.0,0.000000,0.000000,0.000000,1.0
PRED_NON_ENG_LANG_POLISH,121.0,0.016529,0.128028,0.0,0.000000,0.000000,0.000000,1.0
PRED_NON_ENG_LANG_SPANISH,121.0,0.892562,0.310957,0.0,1.000000,1.000000,1.000000,1.0

Checking description of all variables I can make sure that all variable have a count of 121, with min of 0 and max of 1.

Last three steps export three datasets for use in analysis and modeling.

In [7]:
data_dummies.to_csv('processed_data.csv')

In [8]:
data.to_csv('processed_nodummies.csv')

In [9]:
data_scaled.to_csv('processed_scaled.csv')