In [23]:
import pandas as pd
import numpy as np
data=pd.read_csv('C:/Users/vishn/Documents/GitHub/csc478-project/hs_data_all_fields.csv', index_col=0)
data.drop(labels=['Freshmen_On_Track_CPS_Pct_Year_2','Graduation_4_Year_School_Pct_Year_2','Graduation_4_Year_School_Pct_Year_1','Graduation_5_Year_School_Pct_Year_1','College_Enrollment_CPS_Pct_Year_2','College_Enrollment_School_Pct_Year_1','College_Persistence_CPS_Pct_Year_2','Mobility_Rate_Pct','College_Persistence_School_Pct_Year_1','College_Persistence_CPS_Pct_Year_1','College_Enrollment_CPS_Pct_Year_1','Graduation_5_Year_CPS_Pct_Year_1','Graduation_5_Year_CPS_Pct_Year_2','Graduation_4_Year_CPS_Pct_Year_1','Graduation_4_Year_CPS_Pct_Year_2','Freshmen_On_Track_School_Pct_Year_1','Freshmen_On_Track_CPS_Pct_Year_1','Unnamed: 0.1','School_Hours','Legacy_Unit_ID','Finance_ID','Short_Name','Summary','Primary_Category','Is_High_School','Is_Middle_School','Is_Elementary_School','Is_Pre_School','Administrator_Title','Administrator','Phone','Secondary_Contact_Title','Secondary_Contact','Address','City','State','Zip','Fax','Freshman_Start_End_Time','After_School_Hours','Earliest_Drop_Off_Time','Significantly_Modified','Blue_Ribbon_Award_Year','Spot_Light_Award_Year','Improvement_Award_Year','Excellence_Award_Year','Hard_Of_Hearing','Mean_ACT','College_Enrollment_Rate_Mean','School_Year','Progress_Report_Year','Graduation_Rate_Mean','Visual_Impairments','School_Latitude','Classroom_Languages','CPS_School_Profile','Website','Facebook','Twitter','Youtube','Pinterest','Attendance_Boundaries','Grades_Offered_All','Grades_Offered','Student_Count_Native_American','Student_Count_Other_Ethnicity','Student_Count_Asian_Pacific_Islander','Student_Count_Multi','Student_Count_Hawaiian_Pacific_Islander','Student_Count_Ethnicity_Not_Available','Statistics_Description','Demographic_Description','PreK_School_Day','Kindergarten_School_Day','PreSchool_Inclusive','Preschool_Instructional','School_Longitude','School_Longitude','Rating_Statement','Classification_Description','Third_Contact_Title','Third_Contact_Name','Fourth_Contact_Title','Fourth_Contact_Name','Fifth_Contact_Title','Fifth_Contact_Name','Sixth_Contact_Title','Sixth_Contact_Name','Seventh_Contact_Title','Seventh_Contact_Name','Location','Excelerate_Award_Gold_Year','Student_Growth_Description','Growth_Reading_Grades_Tested_Pct_ES','Growth_Reading_Grades_Tested_Label_ES','Growth_Math_Grades_Tested_Pct_ES','Growth_Math_Grades_Tested_Label_ES','Student_Attainment_Description','Attainment_Reading_Pct_ES','Attainment_Reading_Lbl_ES','Attainment_Math_Pct_ES','Attainment_Math_Lbl_ES','Culture_Climate_Description','School_Survey_Student_Response_Rate_Avg_Pct','School_Survey_Teacher_Response_Rate_Avg_Pct','Healthy_School_Certification','Healthy_School_Certification_Description','School_Survey_Student_Response_Rate_Pct','School_Survey_Teacher_Response_Rate_Pct','Creative_School_Certification','Creative_School_Certification_Description','NWEA_Reading_Growth_Grade_3_Pct','NWEA_Reading_Growth_Grade_3_Lbl','NWEA_Reading_Growth_Grade_4_Pct','NWEA_Reading_Growth_Grade_4_Lbl','NWEA_Reading_Growth_Grade_5_Pct','NWEA_Reading_Growth_Grade_5_Lbl','NWEA_Reading_Growth_Grade_6_Pct','NWEA_Reading_Growth_Grade_6_Lbl','NWEA_Reading_Growth_Grade_7_Pct','NWEA_Reading_Growth_Grade_7_Lbl','NWEA_Reading_Growth_Grade_8_Pct','NWEA_Reading_Growth_Grade_8_Lbl','NWEA_Math_Growth_Grade_3_Pct','NWEA_Math_Growth_Grade_3_Lbl','NWEA_Math_Growth_Grade_4_Pct','NWEA_Math_Growth_Grade_4_Lbl','NWEA_Math_Growth_Grade_5_Pct','NWEA_Math_Growth_Grade_5_Lbl','NWEA_Math_Growth_Grade_6_Pct','NWEA_Math_Growth_Grade_6_Lbl','NWEA_Math_Growth_Grade_7_Pct','NWEA_Math_Growth_Grade_7_Lbl','NWEA_Math_Growth_Grade_8_Pct','NWEA_Math_Growth_Grade_8_Lbl','NWEA_Reading_Attainment_Grade_2_Pct','NWEA_Reading_Attainment_Grade_2_Lbl','NWEA_Reading_Attainment_Grade_3_Pct','NWEA_Reading_Attainment_Grade_3_Lbl','NWEA_Reading_Attainment_Grade_4_Pct','NWEA_Reading_Attainment_Grade_4_Lbl','NWEA_Reading_Attainment_Grade_5_Pct','NWEA_Reading_Attainment_Grade_5_Lbl','NWEA_Reading_Attainment_Grade_6_Pct','NWEA_Reading_Attainment_Grade_6_Lbl','NWEA_Reading_Attainment_Grade_7_Pct','NWEA_Reading_Attainment_Grade_7_Lbl','NWEA_Reading_Attainment_Grade_8_Pct','NWEA_Reading_Attainment_Grade_8_Lbl','NWEA_Math_Attainment_Grade_2_Pct','NWEA_Math_Attainment_Grade_2_Lbl','NWEA_Math_Attainment_Grade_3_Pct','NWEA_Math_Attainment_Grade_3_Lbl','NWEA_Math_Attainment_Grade_4_Pct','NWEA_Math_Attainment_Grade_4_Lbl','NWEA_Math_Attainment_Grade_5_Pct','NWEA_Math_Attainment_Grade_5_Lbl','NWEA_Math_Attainment_Grade_6_Pct','NWEA_Math_Attainment_Grade_6_Lbl','NWEA_Math_Attainment_Grade_7_Pct','NWEA_Math_Attainment_Grade_7_Lbl','NWEA_Math_Attainment_Grade_8_Pct','NWEA_Math_Attainment_Grade_8_Lbl','Suspensions_Per_100_Students_Avg_Pct','Misconducts_To_Suspensions_Avg_Pct','Average_Length_Suspension_Year_1_Pct','Average_Length_Suspension_Year_2_Pct','Average_Length_Suspension_Avg_Pct','Behavior_Discipline_Year_1','Behavior_Discipline_Year_2','Student_Attendance_Avg_Pct','Teacher_Attendance_Avg_Pct','One_Year_Dropout_Rate_Avg_Pct','Other_Metrics_Year_1','Other_Metrics_Year_2','Growth_ACT_Grade_11_Lbl','Attainment_ACT_Grade_11_Lbl','Progress_Toward_Graduation_Year_1','Progress_Toward_Graduation_Year_2','State_School_Report_Card_URL','Chronic_Truancy_Pct','Empty_Progress_Report_Message','School_Survey_Rating_Description','Supportive_School_Award_Desc','Parent_Survey_Results_Year','School_Latitude.1','School_Longitude.1','Transportation_Bus','Transportation_El','Transportation_Metra'], axis=1,inplace=True)
data.set_index('School_ID', inplace=True)
name=data['Long_Name']
data.drop(labels='Long_Name', axis=1, inplace=True)
data=data[-data['Graduation_Rate_School'].isna()]
data.describe(include='all')

,School_Type,Student_Count_Total,Student_Count_Low_Income,Student_Count_Special_Ed,Student_Count_English_Learners,Student_Count_Black,Student_Count_Hispanic,Student_Count_White,Student_Count_Asian,ADA_Accessible,Dress_Code,Bilingual_Services,Refugee_Services,Title_1_Eligible,Average_ACT_School,College_Enrollment_Rate_School,Graduation_Rate_School,Overall_Rating,Rating_Status,Student_Growth_Rating,Student_Attainment_Rating,Culture_Climate_Rating,School_Survey_Involved_Families,School_Survey_Supportive_Environment,School_Survey_Ambitious_Instruction,School_Survey_Effective_Leaders,School_Survey_Collaborative_Teachers,School_Survey_Safety,Suspensions_Per_100_Students_Year_1_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_1_Pct,Misconducts_To_Suspensions_Year_2_Pct,School_Survey_School_Community,School_Survey_Parent_Teacher_Partnership,School_Survey_Quality_Of_Facilities,Student_Attendance_Year_1_Pct,Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_1_Pct,Teacher_Attendance_Year_2_Pct,One_Year_Dropout_Rate_Year_1_Pct,One_Year_Dropout_Rate_Year_2_Pct,Growth_ACT_Grade_11_Pct,Attainment_ACT_Grade_11_Pct,Freshmen_On_Track_School_Pct_Year_2,Graduation_5_Year_School_Pct_Year_2,College_Enrollment_School_Pct_Year_2,College_Persistence_School_Pct_Year_2,Supportive_School_Award,lib_cnt,Neighborhood Name,PRED_NON_ENG_LANG,PRED_NON_ENG_PERCENT,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
count,121,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121,121,115,113,121,117.000000,119.000000,121.000000,121,121,121,121,121,121,121,121,121,121,121,88.000000,88.000000,88.000000,88.000000,121,121,121,121.000000,121.000000,85.000000,85.000000,119.000000,119.000000,114.000000,117.000000,117.000000,121.000000,119.000000,115.000000,121,121.000000,121,121,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000
unique,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,2,2,2,NaN,NaN,NaN,6,4,6,6,6,6,5,6,6,5,6,NaN,NaN,NaN,NaN,4,5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,57,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Generally accessible,Y,Y,N,Y,NaN,NaN,NaN,Level 1+,Good Standing,BELOW AVERAGE,BELOW AVERAGE,WELL ORGANIZED,STRONG,NEUTRAL,STRONG,NEUTRAL,NEUTRAL,WEAK,NaN,NaN,NaN,NaN,NOT ENOUGH DATA,NOT ENOUGH DATA,NOT ENOUGH DATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coming Soon,NaN,NEAR WEST SIDE,SPANISH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,78,67,107,111,NaN,NaN,NaN,31,53,40,64,67,44,54,57,48,43,59,NaN,NaN,NaN,NaN,87,87,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,NaN,9,108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,768.181818,617.363636,114.173554,63.553719,284.090909,353.603306,77.528926,35.595041,NaN,NaN,NaN,NaN,NaN,17.467521,58.531092,72.891736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.993182,26.828409,28.785227,29.917045,NaN,NaN,NaN,89.418182,89.026446,94.778824,90.124706,4.885714,4.334454,-0.062281,29.649573,84.720513,72.891736,58.531092,65.806087,NaN,4.297521,NaN,NaN,0.114876,0.056364,0.240306,0.159686,0.223215,0.341702,25269.223140,52.578512
std,NaN,684.097033,474.683105,77.856993,93.828207,287.302628,463.267174,227.987320,86.574205,NaN,NaN,NaN,NaN,NaN,3.152799,19.103521,19.364541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.033535,33.481740,20.519229,22.657156,NaN,NaN,NaN,5.600804,6.803158,0.932112,0.797452,4.754967,4.695769,1.426698,24.946258,11.692449,19.364541,19.103521,15.384860,NaN,2.174261,NaN,NaN,0.145826,0.043006,0.105995,0.071837,0.135779,0.078791,15306.775301,30.505943
min,NaN,38.000000,37.000000,6.000000,0.000000,1.000000,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,13.100000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,61.200000,43.600000,92.500000,88.400000,0.000000,0.000000,-2.500000,3.000000,40.000000,0.000000,0.000000,29.600000,NaN,0.000000,NaN,NaN,0.000000,0.003000,0.034000,0.047000,0.025000,0.135000,8201.000000,1.000000
25%,NaN,307.000000,271.000000,58.000000,4.000000,90.000000,13.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,15.200000,45.500000,67.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.075000,5.925000,14.075000,14.300000,NaN,NaN,NaN,86.900000,87.000000,94.000000,89.600000,1.900000,1.600000,-1.000000,11.000000,78.300000,67.900000,45.500000,58.550000,NaN,3.000000,NaN,NaN,0.010000,0.025000,0.147000,0.100000,0.129000,0.307000,13785.000000,26.000000
50%,NaN,556.000000,479.000000,89.000000,20.000000,196.000000,145.000000,4.000000,1.000000,NaN,NaN,NaN,NaN,NaN,16.800000,59.500000,76.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.750000,11.950000,23.600000,22.400000,NaN,NaN,NaN,90.500000,90.600000,94.900000,90.100000,3.700000,2.900000,-0.400000,22.000000,87.100000,76.300000,59.500000,67.500000,NaN,4.000000,NaN,NaN,0.040000,0.039000,0.217000,0.158000,0.177000,0.369000,19713.000000,52.000000
75%,NaN,1062.000000,855.000000,161.000000,80.000000,355.000000,539.000000,34.000000,10.000000,NaN,NaN,NaN,NaN,NaN,18.500000,74.650000,85.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.925000,32.800000,38.975000,39.250000,NaN,NaN,NaN,93.300000,93.200000,95.500000,90.600000,6.450000,5.450000,0.600000,40.000000,93.200000,85.200000,74.650000,76.900000,NaN,5.000000,NaN,NaN,0.180000,0.074000,0.298000,0.208000,0.285000,0.396000,33385.000000,83.000000
max,NaN,4447.000000,2713.000000,394.000000,502.000000,1468.000000,2377.000000,1567.000000,469.000000,NaN,NaN,NaN,NaN,NaN,29.600000,93.400000,97.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.700000,193.400000,95.400000,100.000000,NaN,NaN,NaN,97.900000,98.000000,97.600000,92.100000,32.300000,33.900000,4.200000,99.000000,100.000000,97.800000,93.400000,97.400000,NaN,11.000000,NaN,NaN,0.450000,0.158000,0.565000,0.359000,0.548000,0.515000,88669.000000,98.000000

In the above step we are deleting irrelevant column names, subsetting the data to school that have graduation rate value filled out, separating names of schools for future use if needed, changing index to school id.

Next is to create change values from fields that have year 1 and year 2 and drop count variables

In [24]:
data['Suspensions_Per_100_Students_Change']=data['Suspensions_Per_100_Students_Year_1_Pct']-data['Suspensions_Per_100_Students_Year_2_Pct']
data['Misconducts_To_Suspensions_Change']=data['Misconducts_To_Suspensions_Year_1_Pct']-data['Misconducts_To_Suspensions_Year_2_Pct']
data['Student_Attendance_Change']=data['Student_Attendance_Year_1_Pct']-data['Student_Attendance_Year_2_Pct']
data['Teacher_Attendance_Change']=data['Teacher_Attendance_Year_1_Pct']-data['Teacher_Attendance_Year_2_Pct']
data['One_Year_Dropout_Rate_Change']=data['One_Year_Dropout_Rate_Year_1_Pct']-data['One_Year_Dropout_Rate_Year_2_Pct']
data.drop(labels=['College_Enrollment_School_Pct_Year_2','Graduation_5_Year_School_Pct_Year_2','Suspensions_Per_100_Students_Year_1_Pct','Suspensions_Per_100_Students_Year_2_Pct','Misconducts_To_Suspensions_Year_1_Pct','Misconducts_To_Suspensions_Year_2_Pct','Student_Attendance_Year_1_Pct','Student_Attendance_Year_2_Pct','Teacher_Attendance_Year_1_Pct','Teacher_Attendance_Year_2_Pct','One_Year_Dropout_Rate_Year_1_Pct','One_Year_Dropout_Rate_Year_2_Pct'],axis=1,inplace=True)

Following step fills in null values:

average for missing values of ACT Score, college enrollment rate, and other percent values related to school or college performance

zeroes for rates of change from previous year; we are assuming that schools that had missing values for suspension, misconduct, teacher attendance and one year drop out rates, had no changces from 2015 to 2016

U for unknown for categorical values that otherwise have a Y/N indicator

In [25]:
data['Average_ACT_School'].fillna(data['Average_ACT_School'].mean(),inplace=True)
data['College_Enrollment_Rate_School'].fillna(data['College_Enrollment_Rate_School'].mean(),inplace=True)
data['Growth_ACT_Grade_11_Pct'].fillna(data['Growth_ACT_Grade_11_Pct'].mean(),inplace=True)
data['Attainment_ACT_Grade_11_Pct'].fillna(data['Attainment_ACT_Grade_11_Pct'].mean(),inplace=True)
data['Freshmen_On_Track_School_Pct_Year_2'].fillna(data['Freshmen_On_Track_School_Pct_Year_2'].mean(),inplace=True)
data['College_Persistence_School_Pct_Year_2'].fillna(data['College_Persistence_School_Pct_Year_2'].mean(),inplace=True)

data['Suspensions_Per_100_Students_Change'].fillna(0,inplace=True)
data['Misconducts_To_Suspensions_Change'].fillna(0,inplace=True)
data['Teacher_Attendance_Change'].fillna(0,inplace=True)
data['One_Year_Dropout_Rate_Change'].fillna(0,inplace=True)

data['Bilingual_Services'].fillna('U',inplace=True)
data['Refugee_Services'].fillna('U',inplace=True)

Some values in the data set had counts of stuned in the school that were part of a group. We calculated rates for those groups using provided counts and student total count. Then, dropped the original count columns.

In [26]:
data['Student_Low_Income_Pct']=data['Student_Count_Low_Income']/data['Student_Count_Total']
data['Student_Special_Ed_Pct']=data['Student_Count_Special_Ed']/data['Student_Count_Total']
data['Student_English_Learners_Pct']=data['Student_Count_English_Learners']/data['Student_Count_Total']
data['Student_Black_Pct']=data['Student_Count_Black']/data['Student_Count_Total']
data['Student_Hispanic_Pct']=data['Student_Count_Hispanic']/data['Student_Count_Total']
data['Student_White_Pct']=data['Student_Count_White']/data['Student_Count_Total']
data['Student_Asian_Pct']=data['Student_Count_Asian']/data['Student_Count_Total']

data.drop(labels=['Student_Count_Low_Income','Student_Count_Special_Ed','Student_Count_English_Learners','Student_Count_Black','Student_Count_Hispanic','Student_Count_White','Student_Count_Asian'], axis=1,inplace=True)

In the following step we are creating a new dataset with dummies for categorical variables

In [27]:
data_dummies=pd.get_dummies(data)

Next step is to create another dataset with all variables scaled from 0 to 1. This data set will be used for regression modeling.

In [28]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit(data_dummies)
data_scaled=pd.DataFrame(min_max.transform(data_dummies),index=data_dummies.index.values,columns=data_dummies.columns.values)

pd.set_option('display.max_columns', 100)
data_scaled.describe(include='all')

,Student_Count_Total,Average_ACT_School,College_Enrollment_Rate_School,Graduation_Rate_School,Growth_ACT_Grade_11_Pct,Attainment_ACT_Grade_11_Pct,Freshmen_On_Track_School_Pct_Year_2,College_Persistence_School_Pct_Year_2,lib_cnt,PRED_NON_ENG_PERCENT,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX,Suspensions_Per_100_Students_Change,Misconducts_To_Suspensions_Change,Student_Attendance_Change,Teacher_Attendance_Change,One_Year_Dropout_Rate_Change,Student_Low_Income_Pct,Student_Special_Ed_Pct,Student_English_Learners_Pct,Student_Black_Pct,Student_Hispanic_Pct,Student_White_Pct,Student_Asian_Pct,School_Type_Career academy,School_Type_Charter,School_Type_Citywide-Option,School_Type_Contract,School_Type_Magnet,School_Type_Military academy,School_Type_Neighborhood,School_Type_Selective enrollment,School_Type_Small,School_Type_Special Education,ADA_Accessible_Fully Accessible,ADA_Accessible_Generally accessible,ADA_Accessible_No/unknown accessibility,Dress_Code_N,Dress_Code_Y,Bilingual_Services_N,Bilingual_Services_U,Bilingual_Services_Y,Refugee_Services_N,Refugee_Services_U,Refugee_Services_Y,...,Neighborhood Name_DOUGLAS,Neighborhood Name_DUNNING,Neighborhood Name_EAST GARFIELD PARK,Neighborhood Name_EAST SIDE,Neighborhood Name_EDGEWATER,Neighborhood Name_ENGLEWOOD,Neighborhood Name_GAGE PARK,Neighborhood Name_GARFIELD RIDGE,Neighborhood Name_GRAND BOULEVARD,Neighborhood Name_GREATER GRAND CROSSING,Neighborhood Name_HERMOSA,Neighborhood Name_HUMBOLDT PARK,Neighborhood Name_IRVING PARK,Neighborhood Name_KENWOOD,Neighborhood Name_LAKE VIEW,Neighborhood Name_LINCOLN PARK,Neighborhood Name_LINCOLN SQUARE,Neighborhood Name_LOOP,Neighborhood Name_LOWER WEST SIDE,Neighborhood Name_MORGAN PARK,Neighborhood Name_MOUNT GREENWOOD,Neighborhood Name_NEAR NORTH SIDE,Neighborhood Name_NEAR SOUTH SIDE,Neighborhood Name_NEAR WEST SIDE,Neighborhood Name_NEW CITY,Neighborhood Name_NORTH CENTER,Neighborhood Name_NORTH LAWNDALE,Neighborhood Name_NORTH PARK,Neighborhood Name_NORWOOD PARK,Neighborhood Name_PORTAGE PARK,Neighborhood Name_PULLMAN,Neighborhood Name_RIVERDALE,Neighborhood Name_ROGERS PARK,Neighborhood Name_ROSELAND,Neighborhood Name_SOUTH CHICAGO,Neighborhood Name_SOUTH LAWNDALE,Neighborhood Name_SOUTH SHORE,Neighborhood Name_UPTOWN,Neighborhood Name_WASHINGTON HEIGHTS,Neighborhood Name_WASHINGTON PARK,Neighborhood Name_WEST ELSDON,Neighborhood Name_WEST ENGLEWOOD,Neighborhood Name_WEST LAWN,Neighborhood Name_WEST RIDGE,Neighborhood Name_WEST TOWN,Neighborhood Name_WOODLAWN,PRED_NON_ENG_LANG_AFRICAN LANGUAGES,PRED_NON_ENG_LANG_CHINESE,PRED_NON_ENG_LANG_POLISH,PRED_NON_ENG_LANG_SPANISH
count,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,...,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.00000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000
mean,0.165612,0.264698,0.626671,0.745314,0.363839,0.277600,0.745342,0.534013,0.390684,0.255280,0.344282,0.388523,0.361173,0.378996,0.543954,0.212112,0.531737,0.497658,0.460626,0.130348,0.527326,0.445522,0.808827,0.169600,0.204971,0.519915,0.387639,0.120364,0.083004,0.033058,0.256198,0.033058,0.016529,0.033058,0.041322,0.363636,0.090909,0.115702,0.016529,0.272727,0.545455,0.181818,0.355372,0.644628,0.396694,0.049587,0.553719,0.884298,0.066116,0.049587,...,0.049587,0.008264,0.024793,0.008264,0.016529,0.041322,0.016529,0.008264,0.016529,0.016529,0.016529,0.033058,0.008264,0.016529,0.008264,0.008264,0.008264,0.016529,0.016529,0.008264,0.008264,0.008264,0.008264,0.07438,0.016529,0.016529,0.024793,0.033058,0.008264,0.016529,0.008264,0.008264,0.016529,0.024793,0.016529,0.057851,0.008264,0.008264,0.016529,0.008264,0.008264,0.016529,0.008264,0.008264,0.057851,0.016529,0.008264,0.082645,0.016529,0.892562
std,0.155159,0.187867,0.202823,0.198001,0.206636,0.255489,0.191599,0.221170,0.197660,0.324058,0.277461,0.199614,0.230247,0.259615,0.207344,0.190222,0.314494,0.094905,0.161228,0.094966,0.352256,0.127153,0.207230,0.139432,0.245138,0.388664,0.347367,0.212846,0.170391,0.179531,0.438348,0.179531,0.128028,0.179531,0.199862,0.483046,0.288675,0.321198,0.128028,0.447214,0.500000,0.387298,0.480616,0.480616,0.491246,0.217992,0.499173,0.321198,0.249517,0.217992,...,0.217992,0.090909,0.156141,0.090909,0.128028,0.199862,0.128028,0.090909,0.128028,0.128028,0.128028,0.179531,0.090909,0.128028,0.090909,0.090909,0.090909,0.128028,0.128028,0.090909,0.090909,0.090909,0.090909,0.26348,0.128028,0.128028,0.156141,0.179531,0.090909,0.128028,0.090909,0.090909,0.128028,0.156141,0.128028,0.234433,0.090909,0.090909,0.128028,0.090909,0.090909,0.128028,0.090909,0.090909,0.234433,0.128028,0.090909,0.276489,0.128028,0.310957
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.061012,0.127273,0.489293,0.694274,0.223881,0.083333,0.670000,0.442478,0.272727,0.022222,0.141935,0.212806,0.169872,0.198853,0.452632,0.069394,0.257732,0.489929,0.411137,0.101770,0.000000,0.394595,0.773343,0.091055,0.019823,0.121060,0.024435,0.004559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.117487,0.230303,0.635974,0.780164,0.328358,0.208333,0.776667,0.547198,0.363636,0.088889,0.232258,0.344633,0.355769,0.290631,0.615789,0.143063,0.525773,0.497006,0.470379,0.121681,0.709677,0.427027,0.886989,0.149572,0.115482,0.441468,0.329032,0.024917,0.007328,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.232252,0.327273,0.798715,0.871166,0.462687,0.375000,0.886667,0.694690,0.454545,0.400000,0.458065,0.497175,0.516026,0.497132,0.686842,0.312969,0.845361,0.511704,0.509479,0.146018,0.774194,0.497297,0.927222,0.221196,0.297831,0.969429,0.710146,0.117013,0.069603,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Checking description of all variables I can make sure that all variable have a count of 121, with min of 0 and max of 1.

Last three steps export three datasets for use in analysis and modeling.

In [29]:
data_dummies.to_csv('processed_data.csv')

In [30]:
data.to_csv('processed_nodummies.csv')

In [31]:
data_scaled.to_csv('processed_scaled.csv')